FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# MicoserviceChapter2

API микросервиса Product Catalog по книге "Хорсдал. Микросервисы на платформе .NET"

## Questions Collection [/questions]

### Create a New Question [POST]

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
            
## Product List [/products?productIds=1,2]

### Product List GET [GET]

+ Response 200 (application/json)

        [
            {
            "productId": "1",
            "productName": "Basic t-shirt",
            "productDescription": "a quiet t-shirt",
            "price": { "amount" : 40, "currency": "eur" },
            "attributes" : [
                {
                "sizes": [ "s", "m", "l"],
                "colors": ["red", "blue", "green"]
                }]
            },
            {
                "productId": "2",
                "productName": "Fancy shirt",
                "productDescription": "a loud t-shirt",
                "price": { "amount" : 50, "currency": "eur" },
                "attributes" : [
                {
                Глава 2 • Простой микросервис для корзины заказов 69
                "sizes": [ "s", "m", "l", "xl"],
                "colors": ["ALL", "Batique"]
                }]
            }
        ]